add docker apt repository for docker compose plugin

diff --git a/images/meat-runner-22.04/dockerfile b/images/meat-runner-22.04/dockerfile
--- a/images/meat-runner-22.04/dockerfile
+++ b/images/meat-runner-22.04/dockerfile
@@ -1,7 +1,7 @@
 FROM ghcr.io/actions/actions-runner:2.315.0
 LABEL org.opencontainers.image.source=https://github.com/synapsestudios/meat-runner
 
-SHELL ["/bin/bash", "--login", "-c"]
+SHELL ["/bin/bash", "--login", "-c", "-o", "pipefail", "-c"]
 WORKDIR /home/runner
 USER root
 # apt-fast prerequisites
@@ -20,6 +20,15 @@ RUN apt-get install -y openjdk-17-jdk
 RUN apt-get install -y gradle
 RUN apt-get install -y npm
 RUN apt-get install -y wget
+
+# Install Docker Compose
+RUN install -m 0755 -d /etc/apt/keyrings
+RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
+RUN chmod a+r /etc/apt/keyrings/docker.asc
+RUN echo \
+    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
+    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
+    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
 RUN apt-get install -y docker-compose-plugin
 
 ARG NVM_VERSION=0.39.7
